USE [pro2sql]
GO

/****** Object:  Table [dbo].[po_mstr]    Script Date: 2/29/2024 12:33:26 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[po_mstr](
	[prrowid] [varchar](36) NOT NULL,
	[po_nbr] [nvarchar](80) NULL,
	[po_vend] [nvarchar](80) NULL,
	[po_ship] [nvarchar](80) NULL,
	[po_ord_date] [datetime] NULL,
	[po_rmks] [nvarchar](80) NULL,
	[po_cr_terms] [nvarchar](80) NULL,
	[po_buyer] [nvarchar](80) NULL,
	[po_shipvia] [nvarchar](30) NULL,
	[po_fob] [nvarchar](30) NULL,
	[po_bill] [nvarchar](80) NULL,
	[po__qad04] [bit] NULL,
	[po_partial] [bit] NULL,
	[po_rev] [decimal](28, 10) NULL,
	[po_stat] [nvarchar](30) NULL,
	[po_ap_acct] [nvarchar](20) NULL,
	[po_ap_cc] [nvarchar](20) NULL,
	[po_frt] [decimal](28, 10) NULL,
	[po_serv_chg] [decimal](28, 10) NULL,
	[po_spec_chg] [decimal](28, 10) NULL,
	[po_tax_pct__1] [decimal](28, 10) NULL,
	[po_tax_pct__2] [decimal](28, 10) NULL,
	[po_tax_pct__3] [decimal](28, 10) NULL,
	[po_disc_pct] [decimal](28, 10) NULL,
	[po_prepaid] [decimal](28, 10) NULL,
	[po_contact] [nvarchar](30) NULL,
	[po_confirm] [bit] NULL,
	[po_cmtindx] [int] NULL,
	[po_print] [bit] NULL,
	[po_cls_date] [datetime] NULL,
	[po_taxable] [bit] NULL,
	[po_user1] [nvarchar](80) NULL,
	[po_user2] [nvarchar](80) NULL,
	[po_curr] [nvarchar](30) NULL,
	[po_ex_rate] [decimal](28, 10) NULL,
	[po_lang] [nvarchar](30) NULL,
	[po_fst_id] [nvarchar](30) NULL,
	[po_pst_id] [nvarchar](30) NULL,
	[po_pst] [bit] NULL,
	[po_duty_type] [nvarchar](30) NULL,
	[po__qad05] [decimal](28, 10) NULL,
	[po__qad07] [nvarchar](80) NULL,
	[po__qad08] [nvarchar](30) NULL,
	[po_site] [nvarchar](80) NULL,
	[po_blanket] [nvarchar](80) NULL,
	[po_rev_date] [datetime] NULL,
	[po__qad02] [int] NULL,
	[po__qad03] [nvarchar](80) NULL,
	[po_contract] [nvarchar](30) NULL,
	[po_del_to] [nvarchar](30) NULL,
	[po_due_date] [datetime] NULL,
	[po_eff_strt] [datetime] NULL,
	[po_eff_to] [datetime] NULL,
	[po_est_value] [decimal](28, 10) NULL,
	[po__qad06] [bit] NULL,
	[po_project] [nvarchar](20) NULL,
	[po_rel_nbr] [int] NULL,
	[po_req_id] [nvarchar](80) NULL,
	[po_type] [nvarchar](30) NULL,
	[po_user_id] [nvarchar](80) NULL,
	[po__qad09] [decimal](28, 10) NULL,
	[po_release] [bit] NULL,
	[po_recurr] [bit] NULL,
	[po_cycl] [nvarchar](30) NULL,
	[po__chr01] [nvarchar](80) NULL,
	[po__chr02] [nvarchar](80) NULL,
	[po__chr03] [nvarchar](80) NULL,
	[po__chr04] [nvarchar](80) NULL,
	[po__chr05] [nvarchar](80) NULL,
	[po__chr06] [nvarchar](80) NULL,
	[po__chr07] [nvarchar](80) NULL,
	[po__chr08] [nvarchar](80) NULL,
	[po__chr09] [nvarchar](80) NULL,
	[po__chr10] [nvarchar](80) NULL,
	[po__dte01] [datetime] NULL,
	[po__dte02] [datetime] NULL,
	[po__dec01] [decimal](28, 10) NULL,
	[po__dec02] [decimal](28, 10) NULL,
	[po__log01] [bit] NULL,
	[po_inv_mthd] [nvarchar](80) NULL,
	[po_fix_rate] [bit] NULL,
	[po_ent_ex] [decimal](20, 10) NULL,
	[po_tax_date] [datetime] NULL,
	[po_fsm_type] [nvarchar](80) NULL,
	[po_bank] [nvarchar](30) NULL,
	[po_pr_list] [nvarchar](80) NULL,
	[po_tax_env] [nvarchar](30) NULL,
	[po_sched] [bit] NULL,
	[po_pr_list2] [nvarchar](80) NULL,
	[po_tax_usage] [nvarchar](80) NULL,
	[po_fix_pr] [bit] NULL,
	[po_sch_mthd] [nvarchar](30) NULL,
	[po_taxc] [nvarchar](30) NULL,
	[po_priced_dt] [datetime] NULL,
	[po_pricing_dt] [datetime] NULL,
	[po_ers_opt] [nvarchar](30) NULL,
	[po_pr_lst_tp] [int] NULL,
	[po_consign_cost_point] [nvarchar](80) NULL,
	[po__qadc02] [nvarchar](80) NULL,
	[po__qadd01] [decimal](28, 10) NULL,
	[po__qadd02] [decimal](28, 10) NULL,
	[po_zero_sched] [int] NULL,
	[po__qadi02] [int] NULL,
	[po_so_nbr] [nvarchar](80) NULL,
	[po_is_btb] [bit] NULL,
	[po_so_hold] [bit] NULL,
	[po_xmit] [nvarchar](30) NULL,
	[po_ex_rate2] [decimal](28, 10) NULL,
	[po_ex_ratetype] [nvarchar](80) NULL,
	[po_exru_seq] [int] NULL,
	[po_ap_sub] [nvarchar](20) NULL,
	[po_crt_int] [decimal](28, 10) NULL,
	[po_consignment] [bit] NULL,
	[po_max_aging_days] [int] NULL,
	[po_app_owner] [nvarchar](30) NULL,
	[po_tot_terms_code] [nvarchar](80) NULL,
	[po_translt_days] [decimal](28, 10) NULL,
	[po_domain] [nvarchar](8) NULL,
	[oid_po_mstr] [decimal](28, 10) NULL,
	[po_trade_sale] [bit] NULL,
	[po_trade_sale_so] [nvarchar](16) NULL,
	[po_incl_iss] [bit] NULL,
	[po__qadc03] [nvarchar](24) NULL,
	[po__qadi03] [int] NULL,
	[po__qadt01] [datetime] NULL,
	[po_daybookset] [nvarchar](8) NULL,
	[po_nrm] [nvarchar](8) NULL,
	[po_tax_in] [bit] NULL,
	[Pro2SrcPDB] [nvarchar](12) NULL,
	[pro2created] [datetime] NULL,
	[pro2modified] [datetime] NULL,
PRIMARY KEY NONCLUSTERED 
(
	[prrowid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[pod_det]    Script Date: 2/29/2024 12:33:26 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[pod_det](
	[prrowid] [varchar](36) NOT NULL,
	[pod_nbr] [nvarchar](80) NULL,
	[pod_due_date] [datetime] NULL,
	[pod_line] [int] NULL,
	[pod_part] [nvarchar](30) NULL,
	[pod_qty_ord] [decimal](28, 10) NULL,
	[pod_qty_rcvd] [decimal](28, 10) NULL,
	[pod_pur_cost] [decimal](28, 10) NULL,
	[pod_std_cost] [decimal](28, 10) NULL,
	[pod_so_job] [nvarchar](80) NULL,
	[pod_qty_chg] [decimal](28, 10) NULL,
	[pod_cost_chg] [decimal](28, 10) NULL,
	[pod_bo_chg] [decimal](28, 10) NULL,
	[pod_acct] [nvarchar](20) NULL,
	[pod_per_date] [datetime] NULL,
	[pod_type] [nvarchar](30) NULL,
	[pod_insp_rqd] [bit] NULL,
	[pod_wo_lot] [nvarchar](80) NULL,
	[pod_vpart] [nvarchar](80) NULL,
	[pod_need] [datetime] NULL,
	[pod_taxable] [bit] NULL,
	[pod_desc] [nvarchar](80) NULL,
	[pod_cc] [nvarchar](20) NULL,
	[pod__qad04__1] [nvarchar](82) NULL,
	[pod__qad04__2] [nvarchar](82) NULL,
	[pod__qad04__3] [nvarchar](82) NULL,
	[pod__qad04__4] [nvarchar](82) NULL,
	[pod__qad04__5] [nvarchar](82) NULL,
	[pod_um] [nvarchar](30) NULL,
	[pod_disc_pct] [decimal](28, 10) NULL,
	[pod_req_nbr] [nvarchar](80) NULL,
	[pod__qad10] [nvarchar](80) NULL,
	[pod_um_conv] [decimal](28, 10) NULL,
	[pod_loc] [nvarchar](80) NULL,
	[pod_serial] [nvarchar](50) NULL,
	[pod_op] [int] NULL,
	[pod_contract] [nvarchar](80) NULL,
	[pod_status] [nvarchar](30) NULL,
	[pod_rev] [nvarchar](30) NULL,
	[pod_cmtindx] [int] NULL,
	[pod_req_line] [int] NULL,
	[pod_project] [nvarchar](20) NULL,
	[pod_ps_chg] [decimal](28, 10) NULL,
	[pod_cst_up] [bit] NULL,
	[pod_rum] [nvarchar](30) NULL,
	[pod_user1] [nvarchar](80) NULL,
	[pod_user2] [nvarchar](80) NULL,
	[pod_vat] [bit] NULL,
	[pod__qad16] [nvarchar](80) NULL,
	[pod__qad06] [nvarchar](30) NULL,
	[pod_pst] [bit] NULL,
	[pod__qad13] [bit] NULL,
	[pod__qad07] [nvarchar](30) NULL,
	[pod_pay_um] [nvarchar](30) NULL,
	[pod_pum_conv] [decimal](28, 10) NULL,
	[pod__qad15] [bit] NULL,
	[pod_site] [nvarchar](80) NULL,
	[pod_rum_conv] [decimal](28, 10) NULL,
	[pod_qty_rtnd] [decimal](28, 10) NULL,
	[pod_blanket] [nvarchar](80) NULL,
	[pod_blnkt_ln] [int] NULL,
	[pod_item_rev_date] [datetime] NULL,
	[pod__qad02] [int] NULL,
	[pod__qad03] [nvarchar](80) NULL,
	[pod__qad05] [bit] NULL,
	[pod__qad08] [datetime] NULL,
	[pod__qad09] [int] NULL,
	[pod__qad11] [nvarchar](80) NULL,
	[pod__qad12] [bit] NULL,
	[pod__qad14] [datetime] NULL,
	[pod_rel_nbr] [int] NULL,
	[pod_rel_qty] [decimal](28, 10) NULL,
	[pod_reason] [nvarchar](80) NULL,
	[pod_request] [nvarchar](80) NULL,
	[pod_approve] [nvarchar](80) NULL,
	[pod__chr01] [nvarchar](80) NULL,
	[pod__chr02] [nvarchar](80) NULL,
	[pod__chr03] [nvarchar](80) NULL,
	[pod__chr04] [nvarchar](80) NULL,
	[pod__chr05] [nvarchar](80) NULL,
	[pod__chr06] [nvarchar](80) NULL,
	[pod__chr07] [nvarchar](80) NULL,
	[pod__chr08] [nvarchar](80) NULL,
	[pod__chr09] [nvarchar](80) NULL,
	[pod__chr10] [nvarchar](80) NULL,
	[pod__dte01] [datetime] NULL,
	[pod__dte02] [datetime] NULL,
	[pod__dec01] [decimal](28, 10) NULL,
	[pod__dec02] [decimal](28, 10) NULL,
	[pod__log01] [bit] NULL,
	[pod_rma_type] [nvarchar](30) NULL,
	[pod_tax_max] [decimal](28, 10) NULL,
	[pod_cum_qty__1] [decimal](28, 10) NULL,
	[pod_cum_qty__2] [decimal](28, 10) NULL,
	[pod_cum_qty__3] [decimal](28, 10) NULL,
	[pod_cum_qty__4] [decimal](28, 10) NULL,
	[pod_cum_date__1] [datetime] NULL,
	[pod_cum_date__2] [datetime] NULL,
	[pod_cum_date__3] [datetime] NULL,
	[pod_cum_date__4] [datetime] NULL,
	[pod_contr_id] [nvarchar](80) NULL,
	[pod_apr_code] [nvarchar](80) NULL,
	[pod_taxc] [nvarchar](30) NULL,
	[pod_po_site] [nvarchar](80) NULL,
	[pod_po_db] [nvarchar](80) NULL,
	[pod_firm_weeks] [int] NULL,
	[pod_mrp_pct] [decimal](28, 10) NULL,
	[pod_raw_weeks] [int] NULL,
	[pod_fab_weeks] [int] NULL,
	[pod_plan_weeks] [int] NULL,
	[pod_curr_rlse_id__1] [nvarchar](82) NULL,
	[pod_curr_rlse_id__2] [nvarchar](82) NULL,
	[pod_curr_rlse_id__3] [nvarchar](82) NULL,
	[pod_sched] [bit] NULL,
	[pod_ord_mult] [decimal](28, 0) NULL,
	[pod_pkg_code] [nvarchar](30) NULL,
	[pod_sch_mrp] [bit] NULL,
	[pod_sch_data] [nvarchar](80) NULL,
	[pod_rlse_nbr] [int] NULL,
	[pod_ship_weeks] [int] NULL,
	[pod_translt_days] [decimal](28, 10) NULL,
	[pod_fsm_type] [nvarchar](80) NULL,
	[pod_sd_pat] [nvarchar](30) NULL,
	[pod_sd_time] [nvarchar](30) NULL,
	[pod_plan_days] [int] NULL,
	[pod_plan_mths] [int] NULL,
	[pod_firm_days] [int] NULL,
	[pod_start_eff__1] [datetime] NULL,
	[pod_start_eff__2] [datetime] NULL,
	[pod_start_eff__3] [datetime] NULL,
	[pod_start_eff__4] [datetime] NULL,
	[pod_end_eff__1] [datetime] NULL,
	[pod_end_eff__2] [datetime] NULL,
	[pod_end_eff__3] [datetime] NULL,
	[pod_end_eff__4] [datetime] NULL,
	[pod_raw_days] [int] NULL,
	[pod_fab_days] [int] NULL,
	[pod_tax_usage] [nvarchar](80) NULL,
	[pod_tax_in] [bit] NULL,
	[pod_sched_chgd] [bit] NULL,
	[pod_pr_list] [nvarchar](80) NULL,
	[pod_dock] [nvarchar](80) NULL,
	[pod_pastdue] [nvarchar](30) NULL,
	[pod_drp_ref] [nvarchar](80) NULL,
	[pod_tax_env] [nvarchar](30) NULL,
	[pod_crt_int] [decimal](28, 10) NULL,
	[pod_translt_hrs] [decimal](28, 10) NULL,
	[pod_sftylt_days] [decimal](28, 10) NULL,
	[pod_sftylt_hrs] [decimal](28, 10) NULL,
	[pod_fix_pr] [bit] NULL,
	[pod_fr_list] [nvarchar](80) NULL,
	[pod_lot_next] [nvarchar](30) NULL,
	[pod_lot_rcpt] [bit] NULL,
	[pod_grade] [nvarchar](30) NULL,
	[pod_expire] [datetime] NULL,
	[pod_rctstat] [nvarchar](80) NULL,
	[pod_assay] [decimal](28, 10) NULL,
	[pod_rctstat_active] [bit] NULL,
	[pod_pricing_dt] [datetime] NULL,
	[pod_pr_lst_tp] [int] NULL,
	[pod_ers_opt] [int] NULL,
	[pod_zero_sched_count] [decimal](28, 10) NULL,
	[pod__qadd02] [decimal](28, 10) NULL,
	[pod__qadd03] [decimal](28, 10) NULL,
	[pod_sod_line] [int] NULL,
	[pod_so_status] [nvarchar](30) NULL,
	[pod_sub_ship_date] [datetime] NULL,
	[pod_sub_type] [nvarchar](80) NULL,
	[pod_sub] [nvarchar](20) NULL,
	[pod_wip_lotser] [nvarchar](30) NULL,
	[pod_pjs_line] [int] NULL,
	[pod_consignment] [bit] NULL,
	[pod_max_aging_days] [int] NULL,
	[pod_multi_due_dates] [bit] NULL,
	[pod_domain] [nvarchar](8) NULL,
	[oid_pod_det] [decimal](28, 10) NULL,
	[pod__qadd04] [decimal](25, 10) NULL,
	[pod__qadt01] [datetime] NULL,
	[Pro2SrcPDB] [nvarchar](12) NULL,
	[pro2created] [datetime] NULL,
	[pro2modified] [datetime] NULL,
PRIMARY KEY NONCLUSTERED 
(
	[prrowid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[prh_hist]    Script Date: 2/29/2024 12:33:26 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[prh_hist](
	[prrowid] [varchar](36) NOT NULL,
	[prh_part] [nvarchar](30) NULL,
	[prh_nbr] [nvarchar](80) NULL,
	[prh_line] [int] NULL,
	[prh_rcvd] [decimal](28, 10) NULL,
	[prh_pur_cost] [decimal](28, 10) NULL,
	[prh_pur_std] [decimal](28, 10) NULL,
	[prh_rcp_date] [datetime] NULL,
	[prh_vend] [nvarchar](80) NULL,
	[prh_receiver] [nvarchar](80) NULL,
	[prh_lot] [nvarchar](80) NULL,
	[prh_ps_nbr] [nvarchar](30) NULL,
	[prh_ps_qty] [decimal](28, 10) NULL,
	[prh_bo_qty] [decimal](28, 10) NULL,
	[prh__qadc02] [nvarchar](80) NULL,
	[prh_xinvoice] [nvarchar](30) NULL,
	[prh_xinv_dt] [datetime] NULL,
	[prh__qadd01] [decimal](28, 10) NULL,
	[prh_xinv_cst] [decimal](28, 10) NULL,
	[prh__qadc03] [nvarchar](80) NULL,
	[prh__qadc04] [nvarchar](80) NULL,
	[prh__qadc05] [nvarchar](80) NULL,
	[prh_rev] [nvarchar](30) NULL,
	[prh_type] [nvarchar](30) NULL,
	[prh_print] [bit] NULL,
	[prh_lbr_std] [decimal](28, 10) NULL,
	[prh_mtl_std] [decimal](28, 10) NULL,
	[prh_bdn_std] [decimal](28, 10) NULL,
	[prh_sub_std] [decimal](28, 10) NULL,
	[prh_buyer] [nvarchar](80) NULL,
	[prh__qad03] [decimal](28, 10) NULL,
	[prh__qad02] [nvarchar](80) NULL,
	[prh_shipto] [nvarchar](80) NULL,
	[prh_cst_up] [bit] NULL,
	[prh_um] [nvarchar](30) NULL,
	[prh_um_conv] [decimal](28, 10) NULL,
	[prh_curr] [nvarchar](30) NULL,
	[prh_ex_rate] [decimal](28, 10) NULL,
	[prh_curr_amt] [decimal](28, 10) NULL,
	[prh_pay_um] [nvarchar](30) NULL,
	[prh_pum_conv] [decimal](28, 10) NULL,
	[prh_user1] [nvarchar](80) NULL,
	[prh_user2] [nvarchar](80) NULL,
	[prh_ovh_std] [decimal](28, 10) NULL,
	[prh_site] [nvarchar](80) NULL,
	[prh_ship] [nvarchar](80) NULL,
	[prh_qty_ord] [decimal](28, 10) NULL,
	[prh_per_date] [datetime] NULL,
	[prh_rcp_type] [nvarchar](30) NULL,
	[prh_reason] [nvarchar](80) NULL,
	[prh_request] [nvarchar](80) NULL,
	[prh_approve] [nvarchar](80) NULL,
	[prh__qad04] [int] NULL,
	[prh_tax_at] [nvarchar](30) NULL,
	[prh__chr01] [nvarchar](80) NULL,
	[prh__chr02] [nvarchar](80) NULL,
	[prh__chr03] [nvarchar](80) NULL,
	[prh__chr04] [nvarchar](80) NULL,
	[prh__chr05] [nvarchar](80) NULL,
	[prh__chr06] [nvarchar](80) NULL,
	[prh__chr07] [nvarchar](80) NULL,
	[prh__chr08] [nvarchar](80) NULL,
	[prh__chr09] [nvarchar](80) NULL,
	[prh__chr10] [nvarchar](80) NULL,
	[prh__dte01] [datetime] NULL,
	[prh__dte02] [datetime] NULL,
	[prh__dte03] [datetime] NULL,
	[prh__dte04] [datetime] NULL,
	[prh__dte05] [datetime] NULL,
	[prh__dec01] [decimal](28, 10) NULL,
	[prh__dec02] [decimal](28, 10) NULL,
	[prh__dec03] [decimal](28, 10) NULL,
	[prh__dec04] [decimal](28, 10) NULL,
	[prh__dec05] [decimal](28, 10) NULL,
	[prh__log01] [bit] NULL,
	[prh__log02] [bit] NULL,
	[prh_rma_type] [nvarchar](30) NULL,
	[prh_fix_rate] [bit] NULL,
	[prh_po_site] [nvarchar](80) NULL,
	[prh_cum_req] [decimal](28, 10) NULL,
	[prh_cum_rcvd] [decimal](28, 10) NULL,
	[prh_fsm_type] [nvarchar](80) NULL,
	[prh_bank] [nvarchar](30) NULL,
	[prh_curr_rlse_id__1] [nvarchar](82) NULL,
	[prh_curr_rlse_id__2] [nvarchar](82) NULL,
	[prh_curr_rlse_id__3] [nvarchar](82) NULL,
	[prh_element] [nvarchar](80) NULL,
	[prh_fix_pr] [bit] NULL,
	[prh_tax_usage] [nvarchar](80) NULL,
	[prh_tax_env] [nvarchar](30) NULL,
	[prh_crt_int] [decimal](28, 10) NULL,
	[prh_tax_in] [bit] NULL,
	[prh_taxc] [nvarchar](30) NULL,
	[prh_vend_lot] [nvarchar](30) NULL,
	[prh_ship_date] [datetime] NULL,
	[prh__qadi01] [int] NULL,
	[prh_ex_rate2] [decimal](28, 10) NULL,
	[prh_ex_ratetype] [nvarchar](80) NULL,
	[prh_exru_seq] [int] NULL,
	[prh__qadc06] [nvarchar](80) NULL,
	[prh__qadc01] [nvarchar](80) NULL,
	[prh_domain] [nvarchar](8) NULL,
	[oid_prh_hist] [decimal](28, 10) NULL,
	[oid_lgd_mstr] [decimal](28, 10) NULL,
	[Pro2SrcPDB] [nvarchar](12) NULL,
	[pro2created] [datetime] NULL,
	[pro2modified] [datetime] NULL,
PRIMARY KEY NONCLUSTERED 
(
	[prrowid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[ps_mstr]    Script Date: 2/29/2024 12:33:26 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ps_mstr](
	[prrowid] [varchar](36) NOT NULL,
	[ps_par] [nvarchar](30) NULL,
	[ps_comp] [nvarchar](30) NULL,
	[ps_ref] [nvarchar](30) NULL,
	[ps_qty_per] [decimal](28, 10) NULL,
	[ps_scrp_pct] [decimal](28, 10) NULL,
	[ps_ps_code] [nvarchar](30) NULL,
	[ps_lt_off] [int] NULL,
	[ps_start] [datetime] NULL,
	[ps_end] [datetime] NULL,
	[ps_rmks] [nvarchar](30) NULL,
	[ps_op] [int] NULL,
	[ps_item_no] [int] NULL,
	[ps_mandatory] [bit] NULL,
	[ps_exclusive] [bit] NULL,
	[ps_process] [nvarchar](80) NULL,
	[ps_qty_type] [nvarchar](30) NULL,
	[ps_user1] [nvarchar](80) NULL,
	[ps_user2] [nvarchar](80) NULL,
	[ps_fcst_pct] [decimal](28, 10) NULL,
	[ps_default] [bit] NULL,
	[ps_group] [nvarchar](80) NULL,
	[ps_critical] [bit] NULL,
	[ps_qty_per_b] [decimal](28, 10) NULL,
	[ps_comp_um] [nvarchar](30) NULL,
	[ps_um_conv] [decimal](28, 10) NULL,
	[ps_assay] [decimal](28, 10) NULL,
	[ps_comm_code] [nvarchar](80) NULL,
	[ps_non_bal] [bit] NULL,
	[ps__qad01] [bit] NULL,
	[ps_userid] [nvarchar](80) NULL,
	[ps_mod_date] [datetime] NULL,
	[ps_batch_pct] [decimal](28, 10) NULL,
	[ps_cmtindx] [int] NULL,
	[ps_start_ecn] [nvarchar](80) NULL,
	[ps_end_ecn] [nvarchar](80) NULL,
	[ps_joint_type] [nvarchar](30) NULL,
	[ps_cop_qty] [decimal](28, 10) NULL,
	[ps_cst_pct] [decimal](28, 10) NULL,
	[ps_prod_pct] [decimal](28, 10) NULL,
	[ps_qty_cons] [decimal](28, 10) NULL,
	[ps_qty_exch] [decimal](28, 10) NULL,
	[ps_qty_diag] [decimal](28, 10) NULL,
	[ps__chr01] [nvarchar](80) NULL,
	[ps__chr02] [nvarchar](80) NULL,
	[ps__dte01] [datetime] NULL,
	[ps__dte02] [datetime] NULL,
	[ps__dec01] [decimal](28, 10) NULL,
	[ps__dec02] [decimal](28, 10) NULL,
	[ps__log01] [bit] NULL,
	[ps__log02] [bit] NULL,
	[ps__qadc01] [nvarchar](80) NULL,
	[ps__qadc02] [nvarchar](80) NULL,
	[ps__qadt01] [datetime] NULL,
	[ps__qadt02] [datetime] NULL,
	[ps__qadt03] [datetime] NULL,
	[ps__qadd01] [decimal](28, 10) NULL,
	[ps__qadd02] [decimal](28, 10) NULL,
	[ps__qadl01] [bit] NULL,
	[ps__qadl02] [bit] NULL,
	[ps_domain] [nvarchar](8) NULL,
	[oid_ps_mstr] [decimal](28, 10) NULL,
	[Pro2SrcPDB] [nvarchar](12) NULL,
	[pro2created] [datetime] NULL,
	[pro2modified] [datetime] NULL,
PRIMARY KEY NONCLUSTERED 
(
	[prrowid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[pt_mstr]    Script Date: 2/29/2024 12:33:26 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[pt_mstr](
	[prrowid] [varchar](36) NOT NULL,
	[pt_part] [nvarchar](30) NULL,
	[pt_desc1] [nvarchar](80) NULL,
	[pt_desc2] [nvarchar](80) NULL,
	[pt_um] [nvarchar](30) NULL,
	[pt__qad13] [nvarchar](30) NULL,
	[pt__qad12] [decimal](28, 10) NULL,
	[pt_draw] [nvarchar](30) NULL,
	[pt_prod_line] [nvarchar](30) NULL,
	[pt_group] [nvarchar](80) NULL,
	[pt_part_type] [nvarchar](80) NULL,
	[pt_status] [nvarchar](80) NULL,
	[pt_abc] [nvarchar](30) NULL,
	[pt_iss_pol] [bit] NULL,
	[pt_phantom] [bit] NULL,
	[pt_loc] [nvarchar](80) NULL,
	[pt__qad01] [decimal](28, 10) NULL,
	[pt__qad02] [decimal](28, 10) NULL,
	[pt_abc_amt] [decimal](28, 10) NULL,
	[pt__qad03] [decimal](28, 10) NULL,
	[pt__qad04] [decimal](28, 10) NULL,
	[pt_avg_int] [int] NULL,
	[pt__qad05] [datetime] NULL,
	[pt_cyc_int] [int] NULL,
	[pt__qad06] [datetime] NULL,
	[pt__qad07] [datetime] NULL,
	[pt__qad08] [datetime] NULL,
	[pt_ms] [bit] NULL,
	[pt_plan_ord] [bit] NULL,
	[pt_mrp] [bit] NULL,
	[pt_ord_pol] [nvarchar](30) NULL,
	[pt_ord_qty] [decimal](28, 10) NULL,
	[pt_ord_per] [int] NULL,
	[pt_sfty_stk] [decimal](28, 0) NULL,
	[pt_sfty_time] [decimal](28, 0) NULL,
	[pt_rop] [decimal](28, 0) NULL,
	[pt_buyer] [nvarchar](80) NULL,
	[pt_vend] [nvarchar](80) NULL,
	[pt__qad09] [decimal](28, 10) NULL,
	[pt_pm_code] [nvarchar](30) NULL,
	[pt_mfg_lead] [decimal](28, 0) NULL,
	[pt_pur_lead] [int] NULL,
	[pt_insp_rqd] [bit] NULL,
	[pt_insp_lead] [int] NULL,
	[pt_cum_lead] [int] NULL,
	[pt_ord_min] [decimal](28, 0) NULL,
	[pt_ord_max] [decimal](28, 0) NULL,
	[pt_ord_mult] [decimal](28, 0) NULL,
	[pt_yield_pct] [decimal](28, 10) NULL,
	[pt__qad16] [decimal](28, 0) NULL,
	[pt_setup] [decimal](28, 10) NULL,
	[pt_setup_ll] [decimal](28, 10) NULL,
	[pt_run_ll] [decimal](28, 10) NULL,
	[pt_run] [decimal](28, 10) NULL,
	[pt_price] [decimal](28, 10) NULL,
	[pt_xmtl_tl] [decimal](28, 10) NULL,
	[pt_xlbr_tl] [decimal](28, 10) NULL,
	[pt_xbdn_tl] [decimal](28, 10) NULL,
	[pt_xsub_tl] [decimal](28, 10) NULL,
	[pt_xmtl_ll] [decimal](28, 10) NULL,
	[pt_xlbr_ll] [decimal](28, 10) NULL,
	[pt_xbdn_ll] [decimal](28, 10) NULL,
	[pt_xsub_ll] [decimal](28, 10) NULL,
	[pt_xtot_cur] [decimal](28, 10) NULL,
	[pt_cur_date] [datetime] NULL,
	[pt_xmtl_stdtl] [decimal](28, 10) NULL,
	[pt_xlbr_stdtl] [decimal](28, 10) NULL,
	[pt_xbdn_stdtl] [decimal](28, 10) NULL,
	[pt_xsub_stdtl] [decimal](28, 10) NULL,
	[pt_xtot_std] [decimal](28, 10) NULL,
	[pt_std_date] [datetime] NULL,
	[pt_ll_code] [int] NULL,
	[pt_abc_qty] [decimal](28, 10) NULL,
	[pt__qad10] [decimal](28, 10) NULL,
	[pt__qad11] [decimal](28, 10) NULL,
	[pt_routing] [nvarchar](30) NULL,
	[pt_lot_ser] [nvarchar](30) NULL,
	[pt_timefence] [int] NULL,
	[pt_xmtl_stdll] [decimal](28, 10) NULL,
	[pt_xlbr_stdll] [decimal](28, 10) NULL,
	[pt_xbdn_stdll] [decimal](28, 10) NULL,
	[pt_xsub_stdll] [decimal](28, 10) NULL,
	[pt_rev] [nvarchar](30) NULL,
	[pt_last_eco] [datetime] NULL,
	[pt__qad15] [bit] NULL,
	[pt__qad17] [bit] NULL,
	[pt_qc_lead] [int] NULL,
	[pt_auto_lot] [bit] NULL,
	[pt_assay] [decimal](28, 10) NULL,
	[pt_batch] [decimal](28, 10) NULL,
	[pt__qad14] [datetime] NULL,
	[pt_user3] [nvarchar](80) NULL,
	[pt_user1] [nvarchar](80) NULL,
	[pt_user2] [nvarchar](80) NULL,
	[pt_net_wt] [decimal](28, 10) NULL,
	[pt_net_wt_um] [nvarchar](30) NULL,
	[pt_size] [decimal](28, 10) NULL,
	[pt_size_um] [nvarchar](30) NULL,
	[pt_taxable] [bit] NULL,
	[pt_taxc] [nvarchar](30) NULL,
	[pt_rollup] [bit] NULL,
	[pt_xovh_ll] [decimal](28, 10) NULL,
	[pt_xovh_tl] [decimal](28, 10) NULL,
	[pt_xovh_stdll] [decimal](28, 10) NULL,
	[pt_xovh_stdtl] [decimal](28, 10) NULL,
	[pt_site] [nvarchar](80) NULL,
	[pt_shelflife] [int] NULL,
	[pt_critical] [bit] NULL,
	[pt_sngl_lot] [bit] NULL,
	[pt_upc] [nvarchar](30) NULL,
	[pt_hazard] [nvarchar](80) NULL,
	[pt_added] [datetime] NULL,
	[pt__chr01] [nvarchar](80) NULL,
	[pt__chr02] [nvarchar](80) NULL,
	[pt__chr03] [nvarchar](80) NULL,
	[pt__chr04] [nvarchar](80) NULL,
	[pt__chr05] [nvarchar](80) NULL,
	[pt__chr06] [nvarchar](80) NULL,
	[pt__chr07] [nvarchar](80) NULL,
	[pt__chr08] [nvarchar](80) NULL,
	[pt__chr09] [nvarchar](80) NULL,
	[pt__chr10] [nvarchar](80) NULL,
	[pt__dte01] [datetime] NULL,
	[pt__dte02] [datetime] NULL,
	[pt__dec01] [decimal](28, 10) NULL,
	[pt__dec02] [decimal](28, 10) NULL,
	[pt__log01] [bit] NULL,
	[pt__log02] [bit] NULL,
	[pt__qad18] [decimal](28, 10) NULL,
	[pt__qad21] [decimal](28, 10) NULL,
	[pt__qad19] [decimal](28, 10) NULL,
	[pt__qad20] [decimal](28, 10) NULL,
	[pt_length] [decimal](28, 10) NULL,
	[pt_height] [decimal](28, 10) NULL,
	[pt_width] [decimal](28, 10) NULL,
	[pt_dim_um] [nvarchar](30) NULL,
	[pt_pkg_code] [nvarchar](30) NULL,
	[pt_network] [nvarchar](30) NULL,
	[pt_ll_drp] [int] NULL,
	[pt_fr_class] [nvarchar](80) NULL,
	[pt_spec_hdlg] [nvarchar](80) NULL,
	[pt_bom_code] [nvarchar](30) NULL,
	[pt_loc_type] [nvarchar](80) NULL,
	[pt_transtype] [nvarchar](80) NULL,
	[pt_cover] [nvarchar](30) NULL,
	[pt_unit_isb] [bit] NULL,
	[pt_article] [nvarchar](30) NULL,
	[pt_po_site] [nvarchar](80) NULL,
	[pt_ship_wt] [decimal](28, 10) NULL,
	[pt_ship_wt_um] [nvarchar](30) NULL,
	[pt_formula] [bit] NULL,
	[pt_dea] [bit] NULL,
	[pt__qad26] [bit] NULL,
	[pt__qad22] [bit] NULL,
	[pt__qad25] [int] NULL,
	[pt__qad24] [int] NULL,
	[pt__qad23] [int] NULL,
	[pt_comm_code] [nvarchar](80) NULL,
	[pt_inst_call] [bit] NULL,
	[pt_sys_type] [nvarchar](30) NULL,
	[pt_tariff] [nvarchar](80) NULL,
	[pt_origin] [nvarchar](30) NULL,
	[pt_sttr] [decimal](28, 10) NULL,
	[pt_mfg_mtbf] [decimal](28, 10) NULL,
	[pt_mfg_mttr] [decimal](28, 10) NULL,
	[pt_fru] [bit] NULL,
	[pt_ven_warr] [bit] NULL,
	[pt_svc_group] [nvarchar](80) NULL,
	[pt_svc_type] [nvarchar](30) NULL,
	[pt_mtbf] [decimal](28, 10) NULL,
	[pt_mttr] [decimal](28, 10) NULL,
	[pt_isb] [bit] NULL,
	[pt_pvm_days] [int] NULL,
	[pt_warr_cd] [nvarchar](80) NULL,
	[pt_mod_date] [datetime] NULL,
	[pt_userid] [nvarchar](80) NULL,
	[pt_obs_date] [datetime] NULL,
	[pt_pvm_bom] [nvarchar](30) NULL,
	[pt_pvm_route] [nvarchar](30) NULL,
	[pt_pvm_um] [nvarchar](30) NULL,
	[pt_rp_bom] [nvarchar](30) NULL,
	[pt_rp_route] [nvarchar](30) NULL,
	[pt_rp_vendor] [nvarchar](80) NULL,
	[pt_rctpo_status] [nvarchar](80) NULL,
	[pt_rollup_id] [nvarchar](80) NULL,
	[pt_spec_grav] [decimal](28, 10) NULL,
	[pt_joint_type] [nvarchar](30) NULL,
	[pt_mfg_pct] [decimal](28, 10) NULL,
	[pt_pur_pct] [decimal](28, 10) NULL,
	[pt_drp_pct] [decimal](28, 10) NULL,
	[pt_pou_code] [nvarchar](30) NULL,
	[pt_wks_avg] [decimal](28, 10) NULL,
	[pt_wks_max] [decimal](28, 10) NULL,
	[pt_wks_min] [decimal](28, 10) NULL,
	[pt_pick_logic] [int] NULL,
	[pt_fiscal_class] [nvarchar](30) NULL,
	[pt_dsgn_grp] [nvarchar](80) NULL,
	[pt_drwg_loc] [nvarchar](80) NULL,
	[pt_ecn_rev] [nvarchar](30) NULL,
	[pt_drwg_size] [nvarchar](30) NULL,
	[pt_model] [nvarchar](30) NULL,
	[pt_repairable] [bit] NULL,
	[pt_rctwo_status] [nvarchar](80) NULL,
	[pt_lot_grp] [nvarchar](80) NULL,
	[pt_rctpo_active] [bit] NULL,
	[pt_rctwo_active] [bit] NULL,
	[pt_break_cat] [nvarchar](30) NULL,
	[pt_fsc_code] [nvarchar](80) NULL,
	[pt_trace_active] [bit] NULL,
	[pt_trace_detail] [bit] NULL,
	[pt_pm_mrp] [bit] NULL,
	[pt_ins_call_type] [nvarchar](80) NULL,
	[pt_ins_bom] [nvarchar](30) NULL,
	[pt_ins_route] [nvarchar](30) NULL,
	[pt_promo] [nvarchar](80) NULL,
	[pt_meter_interval] [decimal](28, 10) NULL,
	[pt_meter_um] [nvarchar](30) NULL,
	[pt_wh] [bit] NULL,
	[pt_btb_type] [nvarchar](30) NULL,
	[pt_cfg_type] [nvarchar](30) NULL,
	[pt_app_owner] [nvarchar](30) NULL,
	[pt_op_yield] [bit] NULL,
	[pt_run_seq1] [nvarchar](80) NULL,
	[pt_run_seq2] [nvarchar](80) NULL,
	[pt_atp_enforcement] [nvarchar](30) NULL,
	[pt_atp_family] [bit] NULL,
	[pt_domain] [nvarchar](8) NULL,
	[oid_pt_mstr] [decimal](28, 10) NULL,
	[pt_classification] [nvarchar](12) NULL,
	[pt_memo_type] [nvarchar](1) NULL,
	[pt_um_group] [nvarchar](16) NULL,
	[pt_opc_threshold] [decimal](20, 10) NULL,
	[pt_pop_code] [nvarchar](16) NULL,
	[pt_whse_part_type] [nvarchar](16) NULL,
	[pt_issue_method] [nvarchar](16) NULL,
	[pt_rep_type] [nvarchar](16) NULL,
	[pt_same_days__1] [int] NULL,
	[pt_same_days__2] [int] NULL,
	[pt_same_days__3] [int] NULL,
	[pt_same_days__4] [int] NULL,
	[pt_same_days__5] [int] NULL,
	[pt_same_days__6] [int] NULL,
	[pt_same_days__7] [int] NULL,
	[pt_same_days__8] [int] NULL,
	[pt_same_days__9] [int] NULL,
	[pt_same_days__10] [int] NULL,
	[pt_invent_days__1] [int] NULL,
	[pt_invent_days__2] [int] NULL,
	[pt_invent_days__3] [int] NULL,
	[pt_invent_days__4] [int] NULL,
	[pt_invent_days__5] [int] NULL,
	[pt_invent_days__6] [int] NULL,
	[pt_invent_days__7] [int] NULL,
	[pt_invent_days__8] [int] NULL,
	[pt_invent_days__9] [int] NULL,
	[pt_invent_days__10] [int] NULL,
	[pt_crit_days] [int] NULL,
	[pt_shelf_offset] [int] NULL,
	[pt_single_trans] [bit] NULL,
	[pt_print_id] [bit] NULL,
	[pt_id_qty] [int] NULL,
	[pt_insp_req] [bit] NULL,
	[pt__qad27] [int] NULL,
	[pt_sample_pct] [int] NULL,
	[pt_insp_freq] [int] NULL,
	[pt_destructive] [bit] NULL,
	[pt_insp_days] [int] NULL,
	[pt_barcode1] [nvarchar](80) NULL,
	[pt_barcode2] [nvarchar](80) NULL,
	[pt_insp_ref] [bit] NULL,
	[pt_random_insp_pct] [decimal](20, 10) NULL,
	[pt_atp_horizon] [int] NULL,
	[pt_gcfg_type] [nvarchar](8) NULL,
	[pt_replenishment_mthd] [nvarchar](8) NULL,
	[pt_gtin_barcode1] [nvarchar](80) NULL,
	[pt_gtin_barcode2] [nvarchar](80) NULL,
	[pt_fiscal_type] [nvarchar](2) NULL,
	[pt_service_code] [nvarchar](4) NULL,
	[pt_freight_nature] [nvarchar](1) NULL,
	[pt_trade_class] [nvarchar](8) NULL,
	[pt_serialized] [int] NULL,
	[pt_sample_qty] [decimal](28, 10) NULL,
	[pt_sourcetype] [nvarchar](80) NULL,
	[pt_nve1_code] [nvarchar](6) NULL,
	[pt_nve2_code] [nvarchar](6) NULL,
	[pt_nve3_code] [nvarchar](6) NULL,
	[pt_nve4_code] [nvarchar](6) NULL,
	[pt_nve5_code] [nvarchar](6) NULL,
	[pt_nve6_code] [nvarchar](6) NULL,
	[pt_nve7_code] [nvarchar](6) NULL,
	[pt_nve8_code] [nvarchar](6) NULL,
	[Pro2SrcPDB] [nvarchar](12) NULL,
	[pro2created] [datetime] NULL,
	[pro2modified] [datetime] NULL,
PRIMARY KEY NONCLUSTERED 
(
	[prrowid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO




/****** Object:  Table [dbo].[ad_mstr]    Script Date: 3/1/2024 8:41:58 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ad_mstr](
	[prrowid] [varchar](36) NOT NULL,
	[ad_addr] [nvarchar](80) NULL,
	[ad_name] [nvarchar](80) NULL,
	[ad_line1] [nvarchar](36) NULL,
	[ad_line2] [nvarchar](36) NULL,
	[ad_city] [nvarchar](30) NULL,
	[ad_state] [nvarchar](30) NULL,
	[ad_zip] [nvarchar](30) NULL,
	[ad_type] [nvarchar](80) NULL,
	[ad_attn] [nvarchar](30) NULL,
	[ad_phone] [nvarchar](30) NULL,
	[ad_ext] [nvarchar](30) NULL,
	[ad_ref] [nvarchar](80) NULL,
	[ad_sort] [nvarchar](80) NULL,
	[ad_country] [nvarchar](30) NULL,
	[ad_attn2] [nvarchar](30) NULL,
	[ad_phone2] [nvarchar](30) NULL,
	[ad_ext2] [nvarchar](30) NULL,
	[ad_fax] [nvarchar](30) NULL,
	[ad_fax2] [nvarchar](30) NULL,
	[ad_line3] [nvarchar](36) NULL,
	[ad_user1] [nvarchar](80) NULL,
	[ad_user2] [nvarchar](80) NULL,
	[ad_lang] [nvarchar](30) NULL,
	[ad_pst_id] [nvarchar](30) NULL,
	[ad_date] [datetime] NULL,
	[ad_county] [nvarchar](30) NULL,
	[ad_temp] [bit] NULL,
	[ad_bk_acct1] [nvarchar](30) NULL,
	[ad_bk_acct2] [nvarchar](30) NULL,
	[ad_format] [int] NULL,
	[ad_vat_reg] [nvarchar](30) NULL,
	[ad_coc_reg] [nvarchar](80) NULL,
	[ad_gst_id] [nvarchar](30) NULL,
	[ad_tax_type] [nvarchar](30) NULL,
	[ad_taxc] [nvarchar](30) NULL,
	[ad_taxable] [bit] NULL,
	[ad_tax_in] [bit] NULL,
	[ad_edi_tpid] [nvarchar](30) NULL,
	[ad_timezone] [nvarchar](80) NULL,
	[ad_mod_date] [datetime] NULL,
	[ad_userid] [nvarchar](80) NULL,
	[ad_edi_id] [nvarchar](30) NULL,
	[ad_edi_ctrl__1] [nvarchar](126) NULL,
	[ad_edi_ctrl__2] [nvarchar](126) NULL,
	[ad_edi_ctrl__3] [nvarchar](126) NULL,
	[ad_edi_ctrl__4] [nvarchar](126) NULL,
	[ad_edi_ctrl__5] [nvarchar](126) NULL,
	[ad_conrep] [nvarchar](30) NULL,
	[ad_barlbl_prt] [nvarchar](max) NULL,
	[ad_barlbl_val] [nvarchar](30) NULL,
	[ad_calendar] [nvarchar](80) NULL,
	[ad_edi_std] [nvarchar](80) NULL,
	[ad_edi_level] [nvarchar](80) NULL,
	[ad__qad01] [nvarchar](80) NULL,
	[ad__qad02] [nvarchar](80) NULL,
	[ad__qad03] [nvarchar](80) NULL,
	[ad__qad04] [nvarchar](80) NULL,
	[ad__qad05] [nvarchar](80) NULL,
	[ad__chr01] [nvarchar](80) NULL,
	[ad__chr02] [nvarchar](80) NULL,
	[ad__chr03] [nvarchar](80) NULL,
	[ad__chr04] [nvarchar](80) NULL,
	[ad__chr05] [nvarchar](80) NULL,
	[ad_tp_loc_code] [nvarchar](30) NULL,
	[ad_ctry] [nvarchar](30) NULL,
	[ad_tax_zone] [nvarchar](30) NULL,
	[ad_tax_usage] [nvarchar](80) NULL,
	[ad_misc1_id] [nvarchar](30) NULL,
	[ad_misc2_id] [nvarchar](30) NULL,
	[ad_misc3_id] [nvarchar](30) NULL,
	[ad_wk_offset] [int] NULL,
	[ad_inv_mthd] [nvarchar](30) NULL,
	[ad_sch_mthd] [nvarchar](30) NULL,
	[ad_po_mthd] [nvarchar](30) NULL,
	[ad_asn_data] [nvarchar](max) NULL,
	[ad_intr_division] [nvarchar](30) NULL,
	[ad_tax_report] [bit] NULL,
	[ad_name_control] [nvarchar](30) NULL,
	[ad_last_file] [bit] NULL,
	[ad_domain] [nvarchar](8) NULL,
	[oid_ad_mstr] [decimal](28, 10) NULL,
	[ad_email] [nvarchar](48) NULL,
	[ad_email2] [nvarchar](48) NULL,
	[ad_bus_relation] [nvarchar](20) NULL,
	[ad_priority] [nvarchar](16) NULL,
	[ad_route] [nvarchar](16) NULL,
	[ad_loadseq] [nvarchar](16) NULL,
	[ad_pick_by_date] [bit] NULL,
	[ad_profile] [nvarchar](16) NULL,
	[ad_address_id] [bigint] NULL,
	[ad_tax_in_city] [bit] NULL,
	[ad_ns_pr_list] [nvarchar](16) NULL,
	[ad_alt_um] [nvarchar](4) NULL,
	[ad_city_code] [nvarchar](20) NULL,
	[Pro2SrcPDB] [nvarchar](12) NULL,
	[pro2created] [datetime] NULL,
	[pro2modified] [datetime] NULL,
PRIMARY KEY NONCLUSTERED 
(
	[prrowid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

/****** Object:  Table [dbo].[address]    Script Date: 3/1/2024 8:41:58 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[address](
	[prrowid] [varchar](36) NOT NULL,
	[address_id] [bigint] NULL,
	[addressstreet1] [nvarchar](36) NULL,
	[addressstreet2] [nvarchar](36) NULL,
	[addressstreet3] [nvarchar](36) NULL,
	[addresszip] [nvarchar](10) NULL,
	[addresscity] [nvarchar](30) NULL,
	[addressname] [nvarchar](36) NULL,
	[addresssearchname] [nvarchar](28) NULL,
	[addresstelephone] [nvarchar](40) NULL,
	[addressemail] [nvarchar](48) NULL,
	[addresswebsite] [nvarchar](60) NULL,
	[addressfax] [nvarchar](40) NULL,
	[addressformat] [int] NULL,
	[addressistemporary] [bit] NULL,
	[country_id] [bigint] NULL,
	[businessrelation_id] [bigint] NULL,
	[addresstype_id] [bigint] NULL,
	[lng_id] [bigint] NULL,
	[state_id] [bigint] NULL,
	[county_id] [bigint] NULL,
	[txztaxzone] [nvarchar](16) NULL,
	[txcltaxcls] [nvarchar](3) NULL,
	[txutaxusage] [nvarchar](8) NULL,
	[addresspostaladdress1] [nvarchar](40) NULL,
	[addresspostaladdress2] [nvarchar](40) NULL,
	[addressissendtopostal] [bit] NULL,
	[addressstate] [nvarchar](20) NULL,
	[addresspostalzip] [nvarchar](40) NULL,
	[addresspostalcity] [nvarchar](20) NULL,
	[addresscounty] [nvarchar](40) NULL,
	[addressistaxable] [bit] NULL,
	[addressistaxincity] [bit] NULL,
	[addressistaxincluded] [bit] NULL,
	[addresstaxidfederal] [nvarchar](18) NULL,
	[addresstaxidstate] [nvarchar](18) NULL,
	[addresstaxidmisc1] [nvarchar](18) NULL,
	[addresstaxidmisc2] [nvarchar](18) NULL,
	[addresstaxidmisc3] [nvarchar](18) NULL,
	[addresstaxdeclaration] [int] NULL,
	[addresslogickeystring] [nvarchar](40) NULL,
	[customshort0] [nvarchar](20) NULL,
	[customshort1] [nvarchar](20) NULL,
	[customshort2] [nvarchar](20) NULL,
	[customshort3] [nvarchar](20) NULL,
	[customshort4] [nvarchar](20) NULL,
	[customshort5] [nvarchar](20) NULL,
	[customshort6] [nvarchar](20) NULL,
	[customshort7] [nvarchar](20) NULL,
	[customshort8] [nvarchar](20) NULL,
	[customshort9] [nvarchar](20) NULL,
	[customcombo0] [nvarchar](20) NULL,
	[customcombo1] [nvarchar](20) NULL,
	[customcombo2] [nvarchar](20) NULL,
	[customcombo3] [nvarchar](20) NULL,
	[customcombo4] [nvarchar](20) NULL,
	[customcombo5] [nvarchar](20) NULL,
	[customcombo6] [nvarchar](20) NULL,
	[customcombo7] [nvarchar](20) NULL,
	[customcombo8] [nvarchar](20) NULL,
	[customcombo9] [nvarchar](20) NULL,
	[customlong0] [nvarchar](max) NULL,
	[customlong1] [nvarchar](max) NULL,
	[customnote] [nvarchar](max) NULL,
	[customdate0] [datetime] NULL,
	[customdate1] [datetime] NULL,
	[customdate2] [datetime] NULL,
	[customdate3] [datetime] NULL,
	[customdate4] [datetime] NULL,
	[custominteger0] [int] NULL,
	[custominteger1] [int] NULL,
	[custominteger2] [int] NULL,
	[custominteger3] [int] NULL,
	[custominteger4] [int] NULL,
	[customdecimal0] [decimal](28, 4) NULL,
	[customdecimal1] [decimal](28, 4) NULL,
	[customdecimal2] [decimal](28, 4) NULL,
	[customdecimal3] [decimal](28, 4) NULL,
	[customdecimal4] [decimal](28, 4) NULL,
	[lastmodifieddate] [datetime] NULL,
	[lastmodifiedtime] [int] NULL,
	[lastmodifieduser] [nvarchar](20) NULL,
	[qadc01] [nvarchar](40) NULL,
	[qadc02] [nvarchar](max) NULL,
	[qadt01] [datetime] NULL,
	[qadd01] [decimal](28, 10) NULL,
	[addresscitycode] [nvarchar](20) NULL,
	[addressexternalvalidationcode] [nvarchar](1) NULL,
	[customshort10] [nvarchar](20) NULL,
	[customshort11] [nvarchar](20) NULL,
	[customshort12] [nvarchar](20) NULL,
	[customshort13] [nvarchar](20) NULL,
	[customshort14] [nvarchar](20) NULL,
	[customshort15] [nvarchar](20) NULL,
	[customshort16] [nvarchar](20) NULL,
	[customshort17] [nvarchar](20) NULL,
	[customshort18] [nvarchar](20) NULL,
	[customshort19] [nvarchar](20) NULL,
	[customcombo10] [nvarchar](20) NULL,
	[customcombo11] [nvarchar](20) NULL,
	[customcombo12] [nvarchar](20) NULL,
	[customcombo13] [nvarchar](20) NULL,
	[customcombo14] [nvarchar](20) NULL,
	[Pro2SrcPDB] [nvarchar](12) NULL,
	[pro2created] [datetime] NULL,
	[pro2modified] [datetime] NULL,
PRIMARY KEY NONCLUSTERED 
(
	[prrowid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

/****** Object:  Table [dbo].[businessrelation]    Script Date: 3/1/2024 8:41:58 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[businessrelation](
	[prrowid] [varchar](36) NOT NULL,
	[businessrelationcode] [nvarchar](20) NULL,
	[businessrelationname1] [nvarchar](36) NULL,
	[businessrelationname2] [nvarchar](36) NULL,
	[businessrelationname3] [nvarchar](60) NULL,
	[businessrelationsearchname] [nvarchar](28) NULL,
	[businessrelationiccode] [nvarchar](20) NULL,
	[businessrelation_id] [bigint] NULL,
	[corporategroup_id] [bigint] NULL,
	[lng_id] [bigint] NULL,
	[obsoletesalespricelist_id] [bigint] NULL,
	[obsoletepurchpricelist_id] [bigint] NULL,
	[obsoletecostpricelist_id] [bigint] NULL,
	[businessrelationisactive] [bit] NULL,
	[businessrelationisinterco] [bit] NULL,
	[businessrelationisincomp] [bit] NULL,
	[businessrelationiscompens] [bit] NULL,
	[businessrelationavrcode] [nvarchar](20) NULL,
	[businessrelationeancode] [nvarchar](20) NULL,
	[businessrelationistaxrep] [bit] NULL,
	[businessrelationislastfill] [bit] NULL,
	[businessrelationnamectrl] [nvarchar](5) NULL,
	[customshort0] [nvarchar](20) NULL,
	[customshort1] [nvarchar](20) NULL,
	[customshort2] [nvarchar](20) NULL,
	[customshort3] [nvarchar](20) NULL,
	[customshort4] [nvarchar](20) NULL,
	[customshort5] [nvarchar](20) NULL,
	[customshort6] [nvarchar](20) NULL,
	[customshort7] [nvarchar](20) NULL,
	[customshort8] [nvarchar](20) NULL,
	[customshort9] [nvarchar](20) NULL,
	[customcombo0] [nvarchar](20) NULL,
	[customcombo1] [nvarchar](20) NULL,
	[customcombo2] [nvarchar](20) NULL,
	[customcombo3] [nvarchar](20) NULL,
	[customcombo4] [nvarchar](20) NULL,
	[customcombo5] [nvarchar](20) NULL,
	[customcombo6] [nvarchar](20) NULL,
	[customcombo7] [nvarchar](20) NULL,
	[customcombo8] [nvarchar](20) NULL,
	[customcombo9] [nvarchar](20) NULL,
	[customlong0] [nvarchar](max) NULL,
	[customlong1] [nvarchar](max) NULL,
	[customnote] [nvarchar](max) NULL,
	[customdate0] [datetime] NULL,
	[customdate1] [datetime] NULL,
	[customdate2] [datetime] NULL,
	[customdate3] [datetime] NULL,
	[customdate4] [datetime] NULL,
	[custominteger0] [int] NULL,
	[custominteger1] [int] NULL,
	[custominteger2] [int] NULL,
	[custominteger3] [int] NULL,
	[custominteger4] [int] NULL,
	[customdecimal0] [decimal](28, 4) NULL,
	[customdecimal1] [decimal](28, 4) NULL,
	[customdecimal2] [decimal](28, 4) NULL,
	[customdecimal3] [decimal](28, 4) NULL,
	[customdecimal4] [decimal](28, 4) NULL,
	[lastmodifieddate] [datetime] NULL,
	[lastmodifiedtime] [int] NULL,
	[lastmodifieduser] [nvarchar](20) NULL,
	[domain_id] [bigint] NULL,
	[businessrelationisdomrestr] [bit] NULL,
	[qadc01] [nvarchar](40) NULL,
	[qadc02] [nvarchar](max) NULL,
	[qadt01] [datetime] NULL,
	[qadd01] [decimal](28, 10) NULL,
	[businessrelationorgtype] [nvarchar](20) NULL,
	[businessrelationcomregisternbr] [nvarchar](20) NULL,
	[businessrelationinstnbr] [nvarchar](20) NULL,
	[businessrelationinstcode] [nvarchar](20) NULL,
	[customshort10] [nvarchar](20) NULL,
	[customshort11] [nvarchar](20) NULL,
	[customshort12] [nvarchar](20) NULL,
	[customshort13] [nvarchar](20) NULL,
	[customshort14] [nvarchar](20) NULL,
	[customcombo10] [nvarchar](20) NULL,
	[customcombo11] [nvarchar](20) NULL,
	[customcombo12] [nvarchar](20) NULL,
	[customcombo13] [nvarchar](20) NULL,
	[customcombo14] [nvarchar](20) NULL,
	[customdate5] [datetime] NULL,
	[customdate6] [datetime] NULL,
	[customdate7] [datetime] NULL,
	[customdate8] [datetime] NULL,
	[customdate9] [datetime] NULL,
	[Pro2SrcPDB] [nvarchar](12) NULL,
	[pro2created] [datetime] NULL,
	[pro2modified] [datetime] NULL,
PRIMARY KEY NONCLUSTERED 
(
	[prrowid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

/****** Object:  Table [dbo].[exr_rate]    Script Date: 3/1/2024 8:44:18 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[exr_rate](
	[prrowid] [varchar](36) NOT NULL,
	[exr_curr1] [nvarchar](30) NULL,
	[exr_curr2] [nvarchar](30) NULL,
	[exr_start_date] [datetime] NULL,
	[exr_end_date] [datetime] NULL,
	[exr_rate] [decimal](28, 10) NULL,
	[exr_rate2] [decimal](28, 10) NULL,
	[exr_ratetype] [nvarchar](80) NULL,
	[exr_mod_userid] [nvarchar](80) NULL,
	[exr_mod_date] [datetime] NULL,
	[exr_user1] [nvarchar](80) NULL,
	[exr_user2] [nvarchar](80) NULL,
	[exr__qadc01] [nvarchar](80) NULL,
	[exr__qadd01] [decimal](28, 10) NULL,
	[exr__qadl01] [bit] NULL,
	[exr__qadt01] [datetime] NULL,
	[exr_domain] [nvarchar](8) NULL,
	[oid_exr_rate] [decimal](28, 10) NULL,
	[Pro2SrcPDB] [nvarchar](12) NULL,
	[pro2created] [datetime] NULL,
	[pro2modified] [datetime] NULL,
PRIMARY KEY NONCLUSTERED 
(
	[prrowid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[company]    Script Date: 3/1/2024 8:58:04 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[company](
	[prrowid] [varchar](36) NOT NULL,
	[company_id] [bigint] NULL,
	[domain_id] [bigint] NULL,
	[companycode] [nvarchar](20) NULL,
	[companyisactive] [bit] NULL,
	[companydomain] [nvarchar](40) NULL,
	[localisationcode] [nvarchar](20) NULL,
	[companydescription] [nvarchar](24) NULL,
	[lastmodifieddate] [datetime] NULL,
	[lastmodifiedtime] [int] NULL,
	[lastmodifieduser] [nvarchar](20) NULL,
	[qadc01] [nvarchar](40) NULL,
	[qadc02] [nvarchar](max) NULL,
	[qadt01] [datetime] NULL,
	[qadd01] [decimal](28, 10) NULL,
	[Pro2SrcPDB] [nvarchar](12) NULL,
	[pro2created] [datetime] NULL,
	[pro2modified] [datetime] NULL,
PRIMARY KEY NONCLUSTERED 
(
	[prrowid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO




/****** Object:  Table [dbo].[tx2_mstr]    Script Date: 3/1/2024 9:22:04 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[tx2_mstr](
	[prrowid] [varchar](36) NOT NULL,
	[tx2_tax_code] [nvarchar](80) NULL,
	[tx2_tax_type] [nvarchar](30) NULL,
	[tx2_pt_taxc] [nvarchar](30) NULL,
	[tx2_tax_usage] [nvarchar](80) NULL,
	[tx2_effdate] [datetime] NULL,
	[tx2_desc] [nvarchar](80) NULL,
	[tx2__qadc01__1] [nvarchar](82) NULL,
	[tx2__qadc01__2] [nvarchar](82) NULL,
	[tx2__qadc02__1] [nvarchar](40) NULL,
	[tx2__qadc02__2] [nvarchar](40) NULL,
	[tx2_tax_pct] [decimal](28, 10) NULL,
	[tx2_method] [nvarchar](30) NULL,
	[tx2_by_line] [bit] NULL,
	[tx2_base] [nvarchar](80) NULL,
	[tx2_min] [decimal](28, 10) NULL,
	[tx2_max] [decimal](28, 10) NULL,
	[tx2_mod_date] [datetime] NULL,
	[tx2_userid] [nvarchar](80) NULL,
	[tx2_pct_recv] [decimal](28, 10) NULL,
	[tx2_trl_taxable] [bit] NULL,
	[tx2_cmtindx] [int] NULL,
	[tx2_curr] [nvarchar](30) NULL,
	[tx2_inv_disc] [bit] NULL,
	[tx2_pmt_disc] [bit] NULL,
	[tx2_update_tax] [bit] NULL,
	[tx2_user1] [nvarchar](80) NULL,
	[tx2_user2] [nvarchar](80) NULL,
	[tx2__chr01] [nvarchar](80) NULL,
	[tx2__chr02] [nvarchar](80) NULL,
	[tx2__dec01] [decimal](28, 10) NULL,
	[tx2__dec02] [decimal](28, 10) NULL,
	[tx2__dte01] [datetime] NULL,
	[tx2__log01] [bit] NULL,
	[tx2__qad01] [nvarchar](80) NULL,
	[tx2__qad02] [nvarchar](80) NULL,
	[tx2__qad03] [bit] NULL,
	[tx2__qad04] [decimal](28, 10) NULL,
	[tx2__qad05] [datetime] NULL,
	[tx2_rcpt_tax_point] [bit] NULL,
	[tx2_ar_acct] [nvarchar](20) NULL,
	[tx2_ar_cc] [nvarchar](20) NULL,
	[tx2_ara_acct] [nvarchar](20) NULL,
	[tx2_ara_cc] [nvarchar](20) NULL,
	[tx2_ara_use] [bit] NULL,
	[tx2_ap_acct] [nvarchar](20) NULL,
	[tx2_ap_cc] [nvarchar](20) NULL,
	[tx2_apr_acct] [nvarchar](20) NULL,
	[tx2_apr_cc] [nvarchar](20) NULL,
	[tx2_apr_use] [bit] NULL,
	[tx2_tax_in] [bit] NULL,
	[tx2_exp_date] [datetime] NULL,
	[tx2_ec_sales_list] [bit] NULL,
	[tx2_ec_process_work] [bit] NULL,
	[tx2_apr_sub] [nvarchar](20) NULL,
	[tx2_ap_sub] [nvarchar](20) NULL,
	[tx2_ara_sub] [nvarchar](20) NULL,
	[tx2_ar_sub] [nvarchar](20) NULL,
	[tx2_ap_disc_acct] [nvarchar](20) NULL,
	[tx2_ap_disc_cc] [nvarchar](20) NULL,
	[tx2_ap_disc_sub] [nvarchar](20) NULL,
	[tx2_ar_disc_acct] [nvarchar](20) NULL,
	[tx2_ar_disc_cc] [nvarchar](20) NULL,
	[tx2_ar_disc_sub] [nvarchar](20) NULL,
	[tx2_group] [nvarchar](80) NULL,
	[tx2_stx_acct] [nvarchar](20) NULL,
	[tx2_stx_cc] [nvarchar](20) NULL,
	[tx2_stx_sub] [nvarchar](20) NULL,
	[tx2_register] [nvarchar](30) NULL,
	[tx2_usage_tax_point] [bit] NULL,
	[tx2_domain] [nvarchar](8) NULL,
	[oid_tx2_mstr] [decimal](28, 10) NULL,
	[tx2_daybookset] [nvarchar](8) NULL,
	[tx2_inv_tx_grp] [nvarchar](30) NULL,
	[tx2_cn_tx_grp] [nvarchar](30) NULL,
	[tx2_voc_tx_grp] [nvarchar](30) NULL,
	[tx2_cr_voc_tx_grp] [nvarchar](30) NULL,
	[tx2_ab_inv_tx_grp] [nvarchar](30) NULL,
	[tx2_ab_cn_tx_grp] [nvarchar](30) NULL,
	[tx2_ret_voc_tx_grp] [nvarchar](30) NULL,
	[tx2_ret_cr_voc_tx_grp] [nvarchar](30) NULL,
	[tx2_ar_cn_acct] [nvarchar](20) NULL,
	[tx2_ar_cn_sub] [nvarchar](20) NULL,
	[tx2_ap_cn_acct] [nvarchar](20) NULL,
	[tx2_ap_cn_sub] [nvarchar](20) NULL,
	[tx2_stx_inv_acct] [nvarchar](20) NULL,
	[tx2_stx_inv_sub] [nvarchar](20) NULL,
	[tx2_stx_cn_acct] [nvarchar](20) NULL,
	[tx2_stx_cn_sub] [nvarchar](20) NULL,
	[tx2_ar_dis_acct] [nvarchar](20) NULL,
	[tx2_ar_dis_sub] [nvarchar](20) NULL,
	[tx2_ap_dis_acct] [nvarchar](20) NULL,
	[tx2_ap_dis_sub] [nvarchar](20) NULL,
	[tx2_dltx_inv_acct] [nvarchar](20) NULL,
	[tx2_dltx_inv_sub] [nvarchar](20) NULL,
	[tx2_dltx_cn_acct] [nvarchar](20) NULL,
	[tx2_dltx_cn_sub] [nvarchar](20) NULL,
	[tx2_ara_cn_acct] [nvarchar](20) NULL,
	[tx2_ara_cn_sub] [nvarchar](20) NULL,
	[tx2_apr_cn_acct] [nvarchar](20) NULL,
	[tx2_apr_cn_sub] [nvarchar](20) NULL,
	[tx2_reverse_charge] [bit] NULL,
	[tx2_stx_dltx_use] [bit] NULL,
	[tx2_cst_code] [nvarchar](2) NULL,
	[tx2_wht_amt_for_100] [decimal](20, 10) NULL,
	[tx2_wht_min_amt] [decimal](20, 10) NULL,
	[tx2_wht_min_nontax_amt] [decimal](20, 10) NULL,
	[tx2_wht_fix_amt] [decimal](20, 10) NULL,
	[tx2_wht_magnetic_file] [bit] NULL,
	[tx2_wht_regime_code] [nvarchar](8) NULL,
	[tx2_wht_rg738_tax_code] [nvarchar](8) NULL,
	[tx2_wht_rg738_operation_code] [nvarchar](8) NULL,
	[tx2_wht_gi_jurisdiction_code] [nvarchar](8) NULL,
	[tx2_markup_pct] [decimal](20, 10) NULL,
	[Pro2SrcPDB] [nvarchar](12) NULL,
	[pro2created] [datetime] NULL,
	[pro2modified] [datetime] NULL,
PRIMARY KEY NONCLUSTERED 
(
	[prrowid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO



/****** Object:  Table [dbo].[paymentcondition]    Script Date: 3/1/2024 9:24:00 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[paymentcondition](
	[prrowid] [varchar](36) NOT NULL,
	[paymentcondition_id] [bigint] NULL,
	[paymentconditionpaymenttyp] [nvarchar](20) NULL,
	[paymentconditionpercentage] [decimal](28, 3) NULL,
	[paymentconditionperiodtype] [nvarchar](20) NULL,
	[paymentconditiondescript] [nvarchar](40) NULL,
	[paymentconditioncode] [nvarchar](8) NULL,
	[paymentconditionisactive] [bit] NULL,
	[paymentconditiondaysmonths] [int] NULL,
	[paymentconditionsuppldays] [int] NULL,
	[paymentconditiongraceday] [int] NULL,
	[paymentconditionlateint] [decimal](20, 2) NULL,
	[paymentconditionduedays] [int] NULL,
	[paymentconditionbasedate] [datetime] NULL,
	[paymentconditionbasedays] [int] NULL,
	[paymentconditiontermsint] [decimal](20, 2) NULL,
	[paymentconditionpddisctype] [nvarchar](20) NULL,
	[paymentconditiondaymthdisc] [int] NULL,
	[paymentconditionsupdaydisc] [int] NULL,
	[customshort0] [nvarchar](20) NULL,
	[customshort1] [nvarchar](20) NULL,
	[customshort2] [nvarchar](20) NULL,
	[customshort3] [nvarchar](20) NULL,
	[customshort4] [nvarchar](20) NULL,
	[customshort5] [nvarchar](20) NULL,
	[customshort6] [nvarchar](20) NULL,
	[customshort7] [nvarchar](20) NULL,
	[customshort8] [nvarchar](20) NULL,
	[customshort9] [nvarchar](20) NULL,
	[customcombo0] [nvarchar](20) NULL,
	[customcombo1] [nvarchar](20) NULL,
	[customcombo2] [nvarchar](20) NULL,
	[customcombo3] [nvarchar](20) NULL,
	[customcombo4] [nvarchar](20) NULL,
	[customcombo5] [nvarchar](20) NULL,
	[customcombo6] [nvarchar](20) NULL,
	[customcombo7] [nvarchar](20) NULL,
	[customcombo8] [nvarchar](20) NULL,
	[customcombo9] [nvarchar](20) NULL,
	[customlong0] [nvarchar](max) NULL,
	[customlong1] [nvarchar](max) NULL,
	[customnote] [nvarchar](max) NULL,
	[customdate0] [datetime] NULL,
	[customdate1] [datetime] NULL,
	[customdate2] [datetime] NULL,
	[customdate3] [datetime] NULL,
	[customdate4] [datetime] NULL,
	[custominteger0] [int] NULL,
	[custominteger1] [int] NULL,
	[custominteger2] [int] NULL,
	[custominteger3] [int] NULL,
	[custominteger4] [int] NULL,
	[customdecimal0] [decimal](28, 4) NULL,
	[customdecimal1] [decimal](28, 4) NULL,
	[customdecimal2] [decimal](28, 4) NULL,
	[customdecimal3] [decimal](28, 4) NULL,
	[customdecimal4] [decimal](28, 4) NULL,
	[lastmodifieddate] [datetime] NULL,
	[lastmodifiedtime] [int] NULL,
	[lastmodifieduser] [nvarchar](20) NULL,
	[qadc01] [nvarchar](40) NULL,
	[qadc02] [nvarchar](max) NULL,
	[qadt01] [datetime] NULL,
	[qadd01] [decimal](28, 10) NULL,
	[billschedule_id] [bigint] NULL,
	[Pro2SrcPDB] [nvarchar](12) NULL,
	[pro2created] [datetime] NULL,
	[pro2modified] [datetime] NULL,
PRIMARY KEY NONCLUSTERED 
(
	[prrowid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO



/****** Object:  Table [dbo].[translationstring]    Script Date: 3/1/2024 9:24:35 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[translationstring](
	[prrowid] [varchar](36) NOT NULL,
	[translationstring_id] [bigint] NULL,
	[parentobject_id] [bigint] NULL,
	[lng_id] [bigint] NULL,
	[translationstringtext] [nvarchar](500) NULL,
	[lastmodifieddate] [datetime] NULL,
	[lastmodifiedtime] [int] NULL,
	[lastmodifieduser] [nvarchar](20) NULL,
	[qadc01] [nvarchar](40) NULL,
	[qadc02] [nvarchar](max) NULL,
	[qadt01] [datetime] NULL,
	[qadd01] [decimal](28, 10) NULL,
	[Pro2SrcPDB] [nvarchar](12) NULL,
	[pro2created] [datetime] NULL,
	[pro2modified] [datetime] NULL,
PRIMARY KEY NONCLUSTERED 
(
	[prrowid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

/****** Object:  Table [dbo].[si_mstr]    Script Date: 3/1/2024 9:46:27 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[si_mstr](
	[prrowid] [varchar](36) NOT NULL,
	[si_site] [nvarchar](80) NULL,
	[si_desc] [nvarchar](80) NULL,
	[si_entity] [nvarchar](30) NULL,
	[si_status] [nvarchar](80) NULL,
	[si_auto_loc] [bit] NULL,
	[si_user1] [nvarchar](80) NULL,
	[si_user2] [nvarchar](80) NULL,
	[si__chr01] [nvarchar](80) NULL,
	[si__chr02] [nvarchar](80) NULL,
	[si__chr03] [nvarchar](80) NULL,
	[si__chr04] [nvarchar](80) NULL,
	[si__chr05] [nvarchar](80) NULL,
	[si__dte01] [datetime] NULL,
	[si__dte02] [datetime] NULL,
	[si__dec01] [decimal](28, 10) NULL,
	[si__dec02] [decimal](28, 10) NULL,
	[si__log01] [bit] NULL,
	[si_gl_set] [nvarchar](80) NULL,
	[si_cur_set] [nvarchar](80) NULL,
	[si_db] [nvarchar](16) NULL,
	[si_xfer_acct] [nvarchar](20) NULL,
	[si_xfer_cc] [nvarchar](20) NULL,
	[si_git_acct] [nvarchar](20) NULL,
	[si_git_cc] [nvarchar](20) NULL,
	[si_canrun] [nvarchar](max) NULL,
	[si_ext_vd] [bit] NULL,
	[si_btb_vend] [nvarchar](80) NULL,
	[si_git_sub] [nvarchar](20) NULL,
	[si_xfer_sub] [nvarchar](20) NULL,
	[si_decl] [nvarchar](80) NULL,
	[si_xfer_ownership] [bit] NULL,
	[si_git_location] [nvarchar](80) NULL,
	[si_domain] [nvarchar](8) NULL,
	[si_type] [bit] NULL,
	[oid_si_mstr] [decimal](28, 10) NULL,
	[si_insp_loc] [nvarchar](8) NULL,
	[si_useplansched_wbs] [bit] NULL,
	[si_mod_userid] [nvarchar](80) NULL,
	[si_mod_date] [datetime] NULL,
	[Pro2SrcPDB] [nvarchar](12) NULL,
	[pro2created] [datetime] NULL,
	[pro2modified] [datetime] NULL,
PRIMARY KEY NONCLUSTERED 
(
	[prrowid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO



/****** Object:  Table [dbo].[loc_mstr]    Script Date: 3/1/2024 9:50:18 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[loc_mstr](
	[prrowid] [varchar](36) NOT NULL,
	[loc_loc] [nvarchar](80) NULL,
	[loc__qad01] [bit] NULL,
	[loc_date] [datetime] NULL,
	[loc_perm] [bit] NULL,
	[loc__qadc01] [nvarchar](80) NULL,
	[loc__qadc02] [nvarchar](80) NULL,
	[loc_project] [nvarchar](20) NULL,
	[loc_site] [nvarchar](80) NULL,
	[loc_status] [nvarchar](80) NULL,
	[loc_user1] [nvarchar](80) NULL,
	[loc_user2] [nvarchar](80) NULL,
	[loc_single] [bit] NULL,
	[loc_type] [nvarchar](80) NULL,
	[loc_cap] [decimal](28, 10) NULL,
	[loc_cap_um] [nvarchar](30) NULL,
	[loc_desc] [nvarchar](80) NULL,
	[loc_phys_addr] [nvarchar](80) NULL,
	[loc_xfer_ownership] [bit] NULL,
	[loc_domain] [nvarchar](8) NULL,
	[oid_loc_mstr] [decimal](28, 10) NULL,
	[Pro2SrcPDB] [nvarchar](12) NULL,
	[pro2created] [datetime] NULL,
	[pro2modified] [datetime] NULL,
PRIMARY KEY NONCLUSTERED 
(
	[prrowid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

